#!/bin/sh
#
# @name QuadrotorX SITL for SIH
#
# @type Quadrotor
#
# @maintainer Romain Chiappinelli <romain.chiap@gmail.com>
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=sihsim}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=quadx}

param set-default SENS_EN_GPSSIM 1
param set-default SENS_EN_BAROSIM 1
param set-default SENS_EN_MAGSIM 1

# Workaround: SIH mag sim doesn't publish fast enough for EKF2 heading alignment
# Use magnetic heading fusion with zero declination
param set-default EKF2_MAG_TYPE 1
param set-default EKF2_MAG_DECL 0.0

# COM_ARM_WO_GPS=2 means "Disabled" — skip all GPS checks
param set-default COM_ARM_WO_GPS 2

# Start height commander on boot
height_commander start

# Auto-test: arm, takeoff, and report altitude
# Run after sensors and EKF have settled
sleep 8
commander arm -f
sleep 3
commander takeoff
sleep 6
listener vehicle_local_position
height_commander status
# Don't shutdown - let the user interact

# Square quadrotor X PX4 numbering
param set-default CA_ROTOR_COUNT 4
param set-default CA_ROTOR0_PX 1
param set-default CA_ROTOR0_PY 1
param set-default CA_ROTOR1_PX -1
param set-default CA_ROTOR1_PY -1
param set-default CA_ROTOR2_PX 1
param set-default CA_ROTOR2_PY -1
param set-default CA_ROTOR2_KM -0.05
param set-default CA_ROTOR3_PX -1
param set-default CA_ROTOR3_PY 1
param set-default CA_ROTOR3_KM -0.05

param set-default PWM_MAIN_FUNC1 101
param set-default PWM_MAIN_FUNC2 102
param set-default PWM_MAIN_FUNC3 103
param set-default PWM_MAIN_FUNC4 104

param set-default SENS_GPS0_DELAY 0
param set-default SENS_GPS1_DELAY 0

param set SIH_VEHICLE_TYPE 0
