#!/bin/sh
#
# @name Gazebo x500 + inverted cart (ceiling)
#
# @type Quadrotor
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}
PX4_GZ_WORLD=${PX4_GZ_WORLD:=ceiling}
PX4_SIM_MODEL=${PX4_SIM_MODEL:=x500_cart}

param set-default SIM_GZ_EN 1

# Holybro H-Flow equivalent: Gazebo optical-flow camera + downward ToF range.
param set-default SIM_GZ_EN_FLOW 1
param set-default SIM_GZ_EN_LIDAR 1
param set-default EKF2_OF_CTRL 1
param set-default EKF2_RNG_A_HMAX 10
param set-default EKF2_RNG_QLTY_T 0.2
param set-default SENS_FLOW_MINHGT 0.08
param set-default SENS_FLOW_MAXHGT 30
param set-default SENS_FLOW_MAXR 7.4

# This model always carries the four upward top-distance sensors.
param set-default CUST_TOP_EN 1
# The canopy underside is about 2.25 m above the initial sensor position.
param set-default CUST_TOP_DIST 3.0
param set-default CUST_TOP_TIME 30.0

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

param set-default CA_ROTOR0_PX 0.13
param set-default CA_ROTOR0_PY 0.22
param set-default CA_ROTOR0_KM 0.05

param set-default CA_ROTOR1_PX -0.13
param set-default CA_ROTOR1_PY -0.2
param set-default CA_ROTOR1_KM 0.05

param set-default CA_ROTOR2_PX 0.13
param set-default CA_ROTOR2_PY -0.22
param set-default CA_ROTOR2_KM -0.05

param set-default CA_ROTOR3_PX -0.13
param set-default CA_ROTOR3_PY 0.2
param set-default CA_ROTOR3_KM -0.05

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 150
param set-default SIM_GZ_EC_MIN2 150
param set-default SIM_GZ_EC_MIN3 150
param set-default SIM_GZ_EC_MIN4 150

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000

# Keep the stock gz_x500 flight tuning unchanged.
param set-default MPC_THR_HOVER 0.6
param set-default NAV_DLL_ACT 2
